name: Package and Release Addon

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch: # Allows manual triggering of the workflow on GitHub Actions page

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Package and Release
        uses: BigWigsMods/packager@v2
        env:
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
          CF_API_KEY: ${{ secrets.CF_API_TOKEN }}
          WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
